---
title: 'Homework 9: ANOVA'
output:
  pdf_document: default
  html_document: default
---
  
----

# NAME: Your Name 
# NETID: Your NetID 
**DUE DATE: November 27, 2019 by 11:59pm**  
----

## Instructions

For this homework:

1. All calculations must be done within your document in code chunks.  Provide all intermediate steps.

2. DO NOT JUST INCLUDE A CALCULATION:  Incude any formulas you are using for a calculation.  You can put these immediately before the code chunk where you actually do the calculation.
    
## Sleep Study Data

This dataset includes observations of the following variables from a random sample of 253 college students.

+------------------+----------------------------------------------+
|   Variable       |            Description                       |
+==================+==============================================+
|   `Gender`       |  1 = Male 0 = Female                         |
+------------------+----------------------------------------------+
|  `ClassYear`     |  Year in school, 1=first year,..., 4=Senior  |
+------------------+----------------------------------------------+
| `LarkOwl`        |  Early riser or night owl?                   |
|                  |  Responses: `Lark`, `Owl`, or `Neither`      |                   
+------------------+----------------------------------------------+
|`NumEarlyClass`   |  Number of early classes each week           |
|                  |  (before 9am)                                |                   
+------------------+----------------------------------------------+
|  `EarlyClass`    |  Indicator for at least 1 early class        |
+------------------+----------------------------------------------+
| `GPA`            |  Grade Point Average                         |                  
+------------------+----------------------------------------------+
|  `ClassesMissed` |  Number of classes missed in a semester      |
+------------------+----------------------------------------------+
|`CognitionZscore` |  Z-score on a test of cognitive skills       |
+------------------+----------------------------------------------+
|`PoorSleepQuality`|  Higher values indicate poorer sleep         |
+------------------+----------------------------------------------+
| `DepressionScore`|  Measure of degree of depression             |
+------------------+----------------------------------------------+
| `AnxietyScore`   |  Measure of amount of anxiety                |
+------------------+----------------------------------------------+
|  `StressScore`   |  Measure of amount of stress                 |
+------------------+----------------------------------------------+
|`DepressionStatus`|  `normal`, `moderate`, or `severe`           |
+------------------+----------------------------------------------+
| `AnxietyStatus`  |  `normal`, `moderate`, or `severe`           |   
+------------------+----------------------------------------------+
|  `Stress`        |  `normal` or `high`                          |
+------------------+----------------------------------------------+
|  `DASScore`      |  Combined score for depression, anxiety      |
|                  |        and stress                            |                 
+------------------+----------------------------------------------+
|  `Happiness`     |  Measure of degree of happiness              |
+------------------+----------------------------------------------+
|  `AlcoholUse`    |  `Abstain`, `Light`, `Moderate`, or `Heavy`  |
+------------------+----------------------------------------------+
|  `Drinks`        |  Number of alcoholic drinks per week         |
+------------------+----------------------------------------------+
| `WeekdaySleep`   | Average hours of sleep on the weekdays       |
+------------------+----------------------------------------------+
| `WeekendSleep`   | Average hours of sleep on the weekend days   |
+------------------+----------------------------------------------+
| `AverageSleep`   | Average hours of sleep for all days          |
+------------------+----------------------------------------------+
| `AllNighter`     | Had an all-nighter this semester?            |
|                  | 1 = yes 0 = no                               |
+------------------+----------------------------------------------+


### Problem 1

Does mean GPA for college students change by class year?  At a significance level of 0.05, test this hypothesis.  The first step is reading in the `SleepStudy` data from the folder for Homework 9.  Then, do the following:


  a) State the null and alternative hypotheses.
  
 
  
  
  b) Compute the total degrees of freedom, the degrees of freedom associated with the numerator of the F statistic, and the error degrees of freedom.
  
 
  
  c) Perform the test in R and include the ANOVA table here.
  

  
  d) What is the sse and mse?  Include how you would calculate the mse from the sse.
  

  
  
  e) What is the ssb and msb? Include how you would calculate the msb from the ssb.
  
 
  
  
  f) What is the realization of the F statistic?  Include a formula.
  
  
  g) What is the p-value of this test?  Calculate the p-value using the `pf()` function in a code chunk here. Verify that this p-value matches the p-value in the ANOVA table.  Should the null hypothesis be rejected based on this p-value? Interpret your conclusion in the context of this problem.



  h) Follow these steps to check the assumptions required to perform an ANOVA test.  
  
    i) Does the assumption of independence hold? (Suppose you could talk to the researchers who collected these data.  What would be relevant to ask them?)


    ii) Check using a graphical method if the assumption of normality holds. Does it hold?



    iii) Check using a graphical method and a formal test if the assumption of equal variance holds.  Does it hold?



    iv) Are the assumptions required to perform an ANOVA hypothesis test met?



### Problem 2

Which of the class years have significantly different mean GPAs?  Conduct all pairwise tests using the Tukey HSD method.  Assume the significance level of these tests is 0.01.  State your conclusion.


### Problem 3  

Does mean GPA for college students change by `AlcoholUse`?  At a significance level of 0.05, test this hypothesis.  For this research question, do the following:

  a) Perform an ANOVA test in R and include the ANOVA table here.

  
  
  b) What is the realization of the test statistic?
  

  
  c) What is the p-value of this test?  Include a formula for the p-value with your answer.  Should the null hypothesis be rejected based on the p-value?  Use a significance level of 0.05.
  

  d) Assuming the assumptions for ANOVA are met, state the conclusion of this test in the context of the research question.
  


### Problem 4

Consider the partially filled in ANOVA table below.  In this study, the means of 5 different treatments were compared.  There was 8 observations for each of the 5 populations.


```{r, results='asis'}
tbl <- matrix(c("G", "A", "H",
                "B", "1837", "3037",
                "C", "D", "",
                "E", "", "",
                "F", "", ""), nrow = 3)
rownames(tbl) <- c("Treatment", "Error", "Total")
colnames(tbl) <- c("Df", "Sum Sq", "Mean Sq", "F value", "Pr(>F)")
knitr::kable(tbl)
```


  a) Determine G, A, and H. 
  
  b) Determine B. 
  
  c) Determine C. 
  
  d) Determine D. 
  
  e) Determine E. 
  
  f) Determine F. 
  

 